@hostLocal = http://192.168.108.69:8080/api
@hostHeruku = https://cafe-react-native-backend.herokuapp.com/api

### Login en heroku

POST {{hostHeruku}}/auth/login
content-type: application/json

{
  "correo": "test1@test.com",
  "password": "123456"
}

### Login en my ip privada

POST {{hostLocal}}/auth/login
content-type: application/json

{
  "correo": "test1@test.com",
  "password": "123456"
}

### New user

POST {{hostLocal}}/usuarios
content-type: application/json

{
  "nombre": "test 5",
  "correo": "test5@test.com",
  "password": "123456"
}

