@hostLocal = http://192.168.131.69:8080/api
@hostHeruku = https://cafe-react-native-backend.herokuapp.com/api

### Login en heroku

POST {{hostHeruku}}/auth/login
content-type: application/json

{
  "correo": "test1@test.com",
  "password": "123456"
}

### Login en mi ip privada

POST {{hostLocal}}/auth/login
content-type: application/json

{
  "correo": "test1@test.com",
  "password": "123456"
}

### Nuevo usuario

POST {{hostLocal}}/usuarios
content-type: application/json

{
  "nombre": "test 5",
  "correo": "test5@test.com",
  "password": "123456"
}

### Mostrar todas las categorias

GET {{hostLocal}}/categorias

### Mostrar todos los productos

GET {{hostLocal}}/productos

